import type { EntityDetail } from "./types";

type Seed = EntityDetail;

const baseDate = new Date("2025-01-01T08:00:00Z").toISOString();

export const SEED: Seed[] = [
  // --- Cusco ---
  {
    id: "1",
    name: "Banco de la Nación",
    type: "Entidad bancaria",
    region: "Cusco",
    city: "Cusco",
    peopleWaiting: 12,
    estimatedWaitMinutes: 28,
    lastUpdatedAt: baseDate,
    activeCounters: 4,
    occupiedCounters: 3,
    capacity: 50,
    address: "Av. Sol 123, Cusco",
    hours: "Lun–Vie 9:00–17:00",
  },
  {
    id: "2",
    name: "Hospital Regional",
    type: "Salud",
    region: "Cusco",
    city: "Cusco",
    peopleWaiting: 7,
    estimatedWaitMinutes: 18,
    lastUpdatedAt: baseDate,
    activeCounters: 3,
    occupiedCounters: 2,
    capacity: 30,
    address: "Av. Cultura 710, Cusco",
    hours: "Lun–Dom 24h (urgencias)",
  },
  {
    id: "3",
    name: "Municipalidad Provincial",
    type: "Trámites",
    region: "Cusco",
    city: "Cusco",
    peopleWaiting: 4,
    estimatedWaitMinutes: 10,
    lastUpdatedAt: baseDate,
    activeCounters: 5,
    occupiedCounters: 2,
    capacity: 40,
    address: "Plaza de Armas s/n, Cusco",
    hours: "Lun–Vie 8:00–16:00",
  },
  {
    id: "4",
    name: "Registro Civil",
    type: "Trámites",
    region: "Cusco",
    city: "Cusco",
    peopleWaiting: 15,
    estimatedWaitMinutes: 35,
    lastUpdatedAt: baseDate,
    activeCounters: 2,
    occupiedCounters: 2,
    capacity: 35,
    address: "Jr. San Andrés 245, Cusco",
    hours: "Lun–Vie 8:30–15:30",
  },
  {
    id: "5",
    name: "SUNAT Cusco",
    type: "Tributos",
    region: "Cusco",
    city: "Cusco",
    peopleWaiting: 9,
    estimatedWaitMinutes: 22,
    lastUpdatedAt: baseDate,
    activeCounters: 3,
    occupiedCounters: 1,
    capacity: 40,
    address: "Av. La Cultura 1500, Cusco",
    hours: "Lun–Vie 9:00–17:00",
  },
  {
    id: "6",
    name: "EPS Sedacusco",
    type: "Servicios",
    region: "Cusco",
    city: "Cusco",
    peopleWaiting: 0,
    estimatedWaitMinutes: 0,
    lastUpdatedAt: baseDate,
    activeCounters: 3,
    occupiedCounters: 0,
    capacity: 30,
    address: "Av. Industrial Lote 4, Cusco",
    hours: "Lun–Vie 8:00–17:00",
  },
  // --- Lima ---
  {
    id: "7",
    name: "Banco BCP Miraflores",
    type: "Entidad bancaria",
    region: "Lima",
    city: "Miraflores",
    peopleWaiting: 22,
    estimatedWaitMinutes: 40,
    lastUpdatedAt: baseDate,
    activeCounters: 6,
    occupiedCounters: 5,
    capacity: 60,
    address: "Av. Larco 345, Miraflores",
    hours: "Lun–Sáb 9:00–18:00",
  },
  {
    id: "8",
    name: "Municipalidad de Lima",
    type: "Trámites",
    region: "Lima",
    city: "Lima Cercado",
    peopleWaiting: 11,
    estimatedWaitMinutes: 25,
    lastUpdatedAt: baseDate,
    activeCounters: 4,
    occupiedCounters: 3,
    capacity: 50,
    address: "Jr. de la Unión 300, Lima",
    hours: "Lun–Vie 8:00–16:00",
  },
  {
    id: "9",
    name: "Hospital Rebagliati",
    type: "Salud",
    region: "Lima",
    city: "Jesús María",
    peopleWaiting: 18,
    estimatedWaitMinutes: 38,
    lastUpdatedAt: baseDate,
    activeCounters: 5,
    occupiedCounters: 4,
    capacity: 45,
    address: "Av. Edgardo Rebagliati 490, Jesús María",
    hours: "Lun–Dom 24h (urgencias)",
  },
  // --- Arequipa ---
  {
    id: "10",
    name: "SUNAT Arequipa",
    type: "Tributos",
    region: "Arequipa",
    city: "Arequipa",
    peopleWaiting: 6,
    estimatedWaitMinutes: 15,
    lastUpdatedAt: baseDate,
    activeCounters: 3,
    occupiedCounters: 2,
    capacity: 35,
    address: "Calle San José 211, Arequipa",
    hours: "Lun–Vie 9:00–17:00",
  },
  {
    id: "11",
    name: "Municipalidad de Arequipa",
    type: "Trámites",
    region: "Arequipa",
    city: "Arequipa",
    peopleWaiting: 3,
    estimatedWaitMinutes: 8,
    lastUpdatedAt: baseDate,
    activeCounters: 4,
    occupiedCounters: 1,
    capacity: 35,
    address: "Plaza de Armas s/n, Arequipa",
    hours: "Lun–Vie 8:00–16:00",
  },
];

export function getSeed(): Seed[] {
  return SEED.map((e) => ({ ...e }));
}

export function findSeed(id: string): Seed | undefined {
  return SEED.find((e) => e.id === id);
}

export function mutate(value: number, range: number, min = 0, max = Infinity): number {
  const delta = Math.floor(Math.random() * (range * 2 + 1)) - range;
  return Math.max(min, Math.min(max, value + delta));
}
